import type { LocationPresetConfig, PublishCategoryMetaConfig } from './config-types';

export const DEFAULT_PUBLISH_CATEGORY_SCHEMA: PublishCategoryMetaConfig[] = [];

export const DEFAULT_LOCATION_PRESETS: LocationPresetConfig[] = [
  { country: '菲律宾', cities: ['马尼拉', '马卡蒂', 'BGC', '塔吉格', '帕赛', '帕拉纳克', '阿拉邦', '奎松', '甲米地', '克拉克', '安吉利斯', '苏比克', '宿务', '达沃', 'MOA', '曼达卢永', '帕西格', '卡加延', '打拉', '邦板牙', '碧瑶', '长滩岛'] },
  { country: '阿联酋', cities: ['迪拜', '阿布扎比', '沙迦', '阿治曼', '拉斯海玛', '迪拜码头', 'JLT', 'Business Bay', 'Deira', 'Bur Dubai', 'International City', '富查伊拉', '乌姆盖万'] },
  { country: '柬埔寨', cities: ['金边', '西港', '暹粒', '波贝', '巴域', '贡布', '国公', '柴桢', '干拉', '七星海', '财通', '拜林', '菩萨', '桔井'] },
  { country: '泰国', cities: ['曼谷', '芭提雅', '普吉', '清迈', '清莱', '合艾', '孔敬', '湄索', '素万那普', '廊曼', '华欣', '苏梅岛', '美塞', '美索'] },
  { country: '斯里兰卡', cities: ['科伦坡', '康提', '加勒', '尼甘布', '拉特纳普勒', '芒特拉维尼亚'] },
  { country: '日本', cities: ['东京', '大阪', '横滨', '名古屋', '福冈', '京都', '札幌', '冲绳'] },
  { country: '韩国', cities: ['首尔', '仁川', '釜山', '济州', '大邱'] },
  { country: '马来西亚', cities: ['吉隆坡', '雪兰莪', '槟城', '柔佛', '新山', '马六甲', '沙巴', '古晋', '云顶', '怡保'] },
  { country: '缅甸', cities: ['仰光', '曼德勒', '内比都', '妙瓦底', '老街', '果敢', '木姐', '大其力', '勐拉', '佤邦', '腊戌', '勐波', '勐平', '当阳', '密支那'] },
  { country: '越南', cities: ['胡志明', '河内', '岘港', '芽庄', '海防', '平阳', '同奈', '芹苴', '富国岛', '大叻', '芒街'] },
  { country: '印尼', cities: ['雅加达', '巴厘岛', '泗水', '万隆', '棉兰', '巴淡', '日惹'] },
  { country: '老挝', cities: ['万象', '琅勃拉邦', '巴色', '磨丁', '金三角', '沙湾拿吉', '丰沙里', '乌多姆赛', '万荣'] },
  { country: '新加坡', cities: ['新加坡', '乌节', '芽笼', '裕廊', '樟宜'] },
  { country: '香港', cities: ['香港岛', '九龙', '新界', '中环', '尖沙咀', '旺角'] },
  { country: '澳门', cities: ['澳门半岛', '氹仔', '路环', '路氹城'] },
  { country: '印度', cities: ['新德里', '孟买', '班加罗尔', '海得拉巴', '金奈', '加尔各答'] },
  { country: '孟加拉', cities: ['达卡', '吉大港', '锡尔赫特'] },
  { country: '尼泊尔', cities: ['加德满都', '博卡拉', '蓝毗尼'] },
  { country: '土耳其', cities: ['伊斯坦布尔', '安卡拉', '安塔利亚', '伊兹密尔'] },
  { country: '塞浦路斯', cities: ['尼科西亚', '利马索尔', '拉纳卡', '北塞'] },
  { country: '亚美尼亚', cities: ['埃里温', '久姆里', '瓦纳佐尔'] },
  { country: '格鲁吉亚', cities: ['第比利斯', '巴统', '库塔伊西'] },
  { country: '塞尔维亚', cities: ['贝尔格莱德', '诺维萨德', '尼什'] },
  { country: '罗马尼亚', cities: ['布加勒斯特', '克卢日', '蒂米什瓦拉', '康斯坦察'] },
  { country: '阿尔巴尼亚', cities: ['地拉那', '都拉斯', '发罗拉'] },
  { country: '黑山', cities: ['波德戈里察', '布德瓦', '科托尔'] },
  { country: '俄罗斯', cities: ['莫斯科', '圣彼得堡', '海参崴', '新西伯利亚'] },
  { country: '哈萨克斯坦', cities: ['阿拉木图', '阿斯塔纳', '奇姆肯特'] },
  { country: '吉尔吉斯斯坦', cities: ['比什凯克', '奥什'] },
  { country: '乌兹别克斯坦', cities: ['塔什干', '撒马尔罕'] },
  { country: '巴西', cities: ['圣保罗', '里约', '巴西利亚', '库里奇巴'] },
  { country: '墨西哥', cities: ['墨西哥城', '坎昆', '瓜达拉哈拉', '蒙特雷', '蒂华纳'] },
  { country: '阿尔及利亚', cities: ['阿尔及尔', '奥兰', '君士坦丁'] },
  { country: '毛里求斯', cities: ['路易港', '居尔皮普', '大湾'] },
  { country: '英国', cities: ['伦敦'] },
  { country: '美国', cities: ['洛杉矶', '纽约', '旧金山', '西雅图'] },
  { country: '加拿大', cities: ['温哥华', '多伦多'] },
  { country: '澳大利亚', cities: ['悉尼', '墨尔本'] },
  { country: '瓦努阿图', cities: ['维拉港'] },
  { country: '马绍尔', cities: ['马朱罗'] },
  { country: '德国', cities: ['柏林', '法兰克福'] },
  { country: '法国', cities: ['巴黎'] },
  { country: '意大利', cities: ['罗马', '米兰'] },
  { country: '西班牙', cities: ['马德里'] },
  { country: '瑞士', cities: ['苏黎世'] },
  { country: '新西兰', cities: ['奥克兰'] },
  { country: '多米尼克', cities: ['罗索'] },
  { country: '葡萄牙', cities: ['里斯本', '波尔图', '法鲁'] },
  { country: '希腊', cities: ['雅典', '塞萨洛尼基', '克里特'] },
  { country: '马耳他', cities: ['瓦莱塔', '斯利马'] },
  { country: '匈牙利', cities: ['布达佩斯', '德布勒森'] },
  { country: '爱尔兰', cities: ['都柏林', '科克'] },
  { country: '荷兰', cities: ['阿姆斯特丹', '鹿特丹', '海牙'] },
  { country: '奥地利', cities: ['维也纳', '萨尔茨堡'] },
  { country: '卢森堡', cities: ['卢森堡市'] },
  { country: '比利时', cities: ['布鲁塞尔', '安特卫普'] },
  { country: '波兰', cities: ['华沙', '克拉科夫'] },
  { country: '捷克', cities: ['布拉格', '布尔诺'] },
  { country: '巴拿马', cities: ['巴拿马城'] },
  { country: '哥斯达黎加', cities: ['圣何塞'] },
  { country: '阿根廷', cities: ['布宜诺斯艾利斯'] },
  { country: '智利', cities: ['圣地亚哥'] },
  { country: '乌拉圭', cities: ['蒙得维的亚'] },
  { country: '安提瓜和巴布达', cities: ['圣约翰'] },
  { country: '圣基茨和尼维斯', cities: ['巴斯特尔'] },
  { country: '圣卢西亚', cities: ['卡斯特里'] },
  { country: '格林纳达', cities: ['圣乔治'] },
];
