export const APP_ROUTES = {
  home: '/',
  messages: '/messages',
  create: '/create',
  profile: '/profile',
  about: '/about',
  sponsor: '/sponsor',
  invite: '/invite',
  inviteRecords: '/invite/records',
  promote: '/promote',
  promotions: '/promotions',
  promotionEffects: '/promotion-effects',
  transactions: '/transactions',
  recharge: '/recharge',
  tuiPlus: '/tui-plus',
  tuiPlusLinkEditor: '/profile/tui-plus-link',
  profileBioEditor: '/profile/bio',
  notificationSettings: '/settings/notifications',
  legacyPromoteHistory: '/promote/history',
  legacyPromotionEffects: '/promote/effects',
} as const;
